#!/bin/bash
cd ../
rm -r drc/__pycache__
rm -r photonics/__pycache__
cd drc
rm *.cpy*
rm cleanermain
rm slcleaner.cp*
rm cleanermain
rm cleanermaster.cp*
rm -r slcleaner_source/build
rm slcleaner_source/cleanermaster.cpp
rm slcleaner_source/slcleaner.cpp
